#!/usr/bin/env python3
"""Build the ServiceNow API tube-style map.

Generated by batch generator. 
"""

import sys
from pathlib import Path

sys.path.insert(0, "/Users/kinlane/GitHub/all/.claude/skills")
from _subway_engine import build_subway  # noqa: E402

ABBREV = {
    'Identification Recon': 'ID Recon',
    'CMDB Data Ingest': 'CMDB Ingest',
    'App Service': 'App Svc',
    'CI/CD Update Set': 'CI/CD US',
    'Performance Analytics': 'Perf. Analytics',
    'Predictive Intelligence': 'Predictive Intel',
    'Metricbase': 'Metricbase TS',
    'AI Assets': 'AI Assets',
    'Virtual Agent': 'Virtual Agent',
    'AWA Offer Work': 'AWA Offer',
    'AWA Agent': 'AWA Agent',
    'OpenFrame': 'OpenFrame',
    'Knowledge Mgmt': 'Knowledge',
    'Service Catalog': 'Svc Catalog',
    'Trouble Ticket': 'Trouble Ticket',
    'Change Mgmt': 'Change Mgmt',
}

LINES = [
    {
        "name": 'Core Tables',
        "color": '#62D84E',
        "stations": [
        ('Table', (270, 195)),
        ('Aggregate', (440, 175)),
        ('Attachment', (610, 165)),
        ('Import Set', (790, 175)),
        ('Batch', (970, 200)),
        ],
    },
    {
        "name": 'ITSM',
        "color": '#1E5BD0',
        "stations": [
        ('Change Mgmt', (270, 310)),
        ('Knowledge Mgmt', (430, 285)),
        ('Service Catalog', (610, 285)),
        ('Trouble Ticket', (790, 285)),
        ('Email', (970, 310)),
        ],
    },
    {
        "name": 'CMDB & Discovery',
        "color": '#7B3FE4',
        "stations": [
        ('CMDB Instance', (270, 425)),
        ('Identification Recon', (470, 405)),
        ('CMDB Meta', (660, 405)),
        ('CMDB Data Ingest', (840, 405)),
        ('App Service', (1010, 425)),
        ],
    },
    {
        "name": 'DevOps & CI/CD',
        "color": '#E68B1F',
        "stations": [
        ('CI/CD', (270, 540)),
        ('CI/CD Update Set', (470, 515)),
        ('DevOps', (660, 515)),
        ('DevOps Config', (840, 515)),
        ],
    },
    {
        "name": 'CSM & HR',
        "color": '#C5318B',
        "stations": [
        ('Case', (270, 660)),
        ('Account', (430, 635)),
        ('Consumer', (590, 635)),
        ('HR', (760, 635)),
        ('Lead', (920, 660)),
        ],
    },
    {
        "name": 'Performance & Analytics',
        "color": '#0E9D6E',
        "stations": [
        ('Performance Analytics', (290, 770)),
        ('Predictive Intelligence', (490, 745)),
        ('Metricbase', (700, 745)),
        ('AI Assets', (880, 770)),
        ],
    },
    {
        "name": 'Workflow & Agent',
        "color": '#5A6275',
        "closed": True,
        "stations": [
        ('Virtual Agent', (790, 815)),
        ('AWA Agent', (905, 815)),
        ('AWA Offer Work', (790, 815)),
        ('OpenFrame', (675, 815)),
        ],
    },
]

URL_OVERRIDES = {
    'Table': 'https://apis.apis.io/apis/servicenow/servicenow-table-api/',
    'Aggregate': 'https://apis.apis.io/apis/servicenow/servicenow-aggregate-api/',
    'Attachment': 'https://apis.apis.io/apis/servicenow/servicenow-attachment-api/',
    'Import Set': 'https://apis.apis.io/apis/servicenow/servicenow-import-set-api/',
    'Batch': 'https://apis.apis.io/apis/servicenow/servicenow-batch-api/',
    'Change Mgmt': 'https://apis.apis.io/apis/servicenow/servicenow-change-management-api/',
    'Knowledge Mgmt': 'https://apis.apis.io/apis/servicenow/servicenow-knowledge-management-api/',
    'Service Catalog': 'https://apis.apis.io/apis/servicenow/servicenow-service-catalog-api/',
    'Trouble Ticket': 'https://apis.apis.io/apis/servicenow/servicenow-trouble-ticket-api/',
    'Email': 'https://apis.apis.io/apis/servicenow/servicenow-email-api/',
    'CMDB Instance': 'https://apis.apis.io/apis/servicenow/servicenow-cmdb-instance-api/',
    'Identification Recon': 'https://apis.apis.io/apis/servicenow/servicenow-identification-reconciliation-api/',
    'CMDB Meta': 'https://apis.apis.io/apis/servicenow/servicenow-cmdb-meta-api/',
    'CMDB Data Ingest': 'https://apis.apis.io/apis/servicenow/servicenow-cmdb-data-ingestion-api/',
    'App Service': 'https://apis.apis.io/apis/servicenow/servicenow-application-service-api/',
    'CI/CD': 'https://apis.apis.io/apis/servicenow/servicenow-cicd-api/',
    'CI/CD Update Set': 'https://apis.apis.io/apis/servicenow/servicenow-cicd-update-set-api/',
    'DevOps': 'https://apis.apis.io/apis/servicenow/servicenow-devops-api/',
    'DevOps Config': 'https://apis.apis.io/apis/servicenow/servicenow-devops-config-api/',
    'Case': 'https://apis.apis.io/apis/servicenow/servicenow-case-api/',
    'Account': 'https://apis.apis.io/apis/servicenow/servicenow-account-api/',
    'Consumer': 'https://apis.apis.io/apis/servicenow/servicenow-consumer-api/',
    'HR': 'https://apis.apis.io/apis/servicenow/servicenow-hr-api/',
    'Lead': 'https://apis.apis.io/apis/servicenow/servicenow-lead-api/',
    'Performance Analytics': 'https://apis.apis.io/apis/servicenow/servicenow-performance-analytics-api/',
    'Predictive Intelligence': 'https://apis.apis.io/apis/servicenow/servicenow-predictive-intelligence-api/',
    'Metricbase': 'https://apis.apis.io/apis/servicenow/servicenow-metricbase-time-series-api/',
    'AI Assets': 'https://apis.apis.io/apis/servicenow/servicenow-ai-assets-api/',
    'Virtual Agent': 'https://apis.apis.io/apis/servicenow/servicenow-virtual-agent-bot-integration-api/',
    'AWA Agent': 'https://apis.apis.io/apis/servicenow/servicenow-awa-agent-api/',
    'AWA Offer Work': 'https://apis.apis.io/apis/servicenow/servicenow-awa-offer-work-api/',
    'OpenFrame': 'https://apis.apis.io/apis/servicenow/servicenow-openframe-api/',
}


def main():
    seen = set()
    n_unique = 0
    for ln in LINES:
        for (st, _) in ln["stations"]:
            if st not in seen:
                n_unique += 1
                seen.add(st)
    build_subway(
        title='The ServiceNow API · Underground Map',
        subtitle=f"{n_unique} APIs · {len(LINES)} functional lines · click any station for the apis.io page",
        lines=LINES,
        abbrev=ABBREV,
        source_label='Source: servicenow/openapi · github.com/api-evangelist/servicenow',
        out_dir=Path(__file__).resolve().parent,
        out_basename='servicenow-subway-map',
        provider_id='servicenow',
        station_url_overrides=URL_OVERRIDES,
    )


if __name__ == "__main__":
    main()
